config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'money#index'
  resources :money
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/money.rb
class Money < ApplicationRecord
	validates :title, :amount, presence: true

	def self.balance
		where("amount > ? ",0).sum(:amount)
	end	

	def self.debt
		where("amount < ? ",0).sum(:amount)
	end

	def self.total
		sum(:amount)
	end

	def self.date
		@date=Money.date
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/money_controller.rb
class MoneyController < ApplicationController
	def index
		@money= Money.all
		@balance = Money.balance
		@debt = Money.debt
		@total = Money.total
	end
	
	def create
		@money= Money.create(money_params)
		if @money.valid?
			flash[:success]="Your transaction has been posted!"
		else 
			flash[:alert]= "Sorry, Something is Wrong, Try Again!"
		end
		redirect_to root_path
	end

	def edit
		@money= Money.find(params[:id]) 
	end

	def update
		@money= Money.find(params[:id])
		if @money.update(money_params)
			flash[:success]="Transaction Updated"
			redirect_to root_path
		else 
			flash[:alert]="Sorry, Something is Wrong, Try Again!"
			redirect_to edit_money_path(params[:id])
		end 
	end

	def destroy
		@money= Money.find(params[:id])
		@money.destroy
		flash[:success]="Transaction Destroyed"
		redirect_to root_path
	end 

	
	private
	
	def money_params
    	params.require(:money).permit(:title, :amount, :date)
  	end
end

app/helpers/add_records_helper.rb
module AddRecordsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/money_helper.rb
module MoneyHelper
end

app/views/add_records/add_records.html.erb
<%= simple_form_for Money.new do |f| %>
<%= f.input :title %>
<%= f.input :amount %>
<%= f.submit 'Submit' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link href="https://fonts.googleapis.com/css?family=PT+Sans:400,700|Ubuntu:400,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
  </head>

  <body>

  <div id="wrap">
 		<%= render 'shared/nav' %>
    <%= render 'shared/flash' %>
	 <div class = "container">

    	<%= yield %>
    </div>
	</div>
    
    <%= render 'shared/foot' %>

  </body>
</html>

app/views/money/addmoney.html.erb
<div class="add_button"
<%= simple_form_for Money.new do |f| %>
<div class="modal-body">
<%= f.input :title %>
<%= f.input :amount %>
<%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

</div>

app/views/money/edit.html.erb
<div class="text">
<h1> Revise Transaction.</h1>
</div>
<div class="edit_buttons">
<%= simple_form_for @money, method: :patch do |f| %>
<%= f.input :title %>
<%= f.input :amount %>
<%= f.submit 'Update Record', class: 'btn btn-primary' %>
<% end %>
	
</div>

app/views/money/index.html.erb
<div class="trans_table">
  <table>
    <ul style="list-style-type: none">
      <li><h1>    Balance: <%= @balance %>  </h1> </li>
      <li><h1>   Debt: <%= @debt %>  </h1> </li>
      <li><h1> Total: <%= @total %> </h1> </li> 
    </ul>
  </table>
</div>

<table class="table" id="money-table">
 
  <tr>
    <th>  Created at </th>
    <th>  Title     </th>
    <th>  amount    </th>
  </tr>

  <% @money.each do |money| %>
    <tr> 
      <td> <%= money.date.strftime("%b/%d/%Y") %> </td>
      <td> <%= money.title %> </td>
      <td>	<kbd><%=money.amount %> 	</kbd>	</td>
      <td> <%= link_to 'Edit', edit_money_path(money), class: 'btn btn-warning' %> </td>
      <td> <%= link_to 'Delete', money_path(money),  method: :delete, class: 'btn btn-danger', data: {Confirm: "Are you sure?"} %> </td>
    </tr>
  <% end %> 
 
 </table>

app/views/money/new.html.erb
<%= simple_form_for Money.new do |f| %>
<div class="modal-body">
<%= f.input :title %>
<%= f.input :amount %>
<%= f.input :date %>
</div>
<div class="buttons">
<%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == "notice" %>
    <p class="alert alert-info alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= notice %></p>
  <% elsif message_type == "alert" %>
    <p class="alert alert-danger alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= alert %></p>
  <% else %>
    <div class="alert alert-<%= message_type %> alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= message %></div>
  <% end %>
<% end %>

app/views/shared/_foot.html.erb
<div class="footer text-center">
    <p>© Yankexe <%= Date.today.year %> All Rights Reserved</p>    
  </div>

app/views/shared/_nav.html.erb
<nav>
	<nav class="navbar navbar-inverse">
 		<div class="container-fluid">
   		<div class="navbar-header">
      		 <%= link_to 'Wallet', root_path %>
    	</div>

 			<div class="button">
 				<ul>
 		<li> <%= link_to 'Add Record', new_money_path, class: 'btn btn-primary'%></li>
 		</ul>
 	</div>
   			
	</div>


 	
 
 </nav>